//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Nationalid { get; set; }
        public string Sex { get; set; }
        public int Height { get; set; }
        public double Weight { get; set; }
        public int FatPercentage { get; set; }
        public string Goal { get; set; }
        public string Pills { get; set; }
        public string Supplement { get; set; }
        public string RedirectedBy { get; set; }
        public int Price { get; set; }
        public int RMR { get; set; }
        public int UserId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual User User { get; set; }
    }
}
